/**
 * @file properties.now.ts
 * @description Application system properties (`sys_properties`) configuration.
 * Stores platform role identifiers used in script validations and UI activity formatter settings.
 * @module properties
 * @scope x_1297430_sncadmin
 * @sdk ServiceNow Now SDK 4.12.2
 */

import { Property } from '@servicenow/sdk/core'

// ─── Platform Role Identifiers ───

/**
 * Sys ID of the well-known platform 'admin' role.
 * Used by the client-callable script include to check whether a user already possesses admin access.
 */
export const adminRoleSysId = Property({
    $id: Now.ID['property-admin-role-sys-id'],
    name: 'x_1297430_sncadmin.admin-role-sys_id',
    value: '2831a114c611228501d4ea6c309d626d',
    ignoreCache: true,
})

/**
 * Sys ID of the well-known platform 'security_admin' role.
 * Used by the client-callable script include to check whether a user already possesses elevated security_admin access.
 */
export const securityAdminRoleSysId = Property({
    $id: Now.ID['property-security-admin-role-sys-id'],
    name: 'x_1297430_sncadmin.scurity_admin-role-sys_id',
    value: 'b2d8f7130a0a0baa5bf52498ecaadeb4',
    ignoreCache: true,
})

// ─── Activity Formatter Configuration ───

/**
 * Fields displayed in the Activity Formatter on the Temporary Access form.
 * Uses the platform-mandated 'glide.ui.<table_name>_activity.fields' naming convention required by the activity stream formatter
 * (Note: The Now SDK may issue warning TS11 regarding property naming conventions, but this exact format is required by ServiceNow UI).
 */
export const temporaryAccessActivityFields = Property({
    $id: Now.ID['property-temporary-access-activity-fields'],
    name: 'glide.ui.x_1297430_sncadmin_temporary_access_activity.fields',
    value: 'access_granted,additional_comment,sys_created_on,sys_created_by,end_date,granted,number,request_ticket,start_date,sys_tags,sys_updated_on,sys_updated_by,sys_mod_count,user,*Attachments*,*EmailCorrespondence*,*Sidebar discussion*,*EmailAutogenerated*,*Relations*,*Sidebar posted message*',
    description: 'Temporary Access activity formatter fields',
})
